services:
  client:
    container_name: debug_dev_client
    build: ./client
    image: debug_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  api:
    container_name: debug_dev_api
    ports: 
      - 5000:5000
    environment: 
      - PGUSER=treasury
      - PGHOST=db
      - PGPASSWORD=stockspass
      - PGDATABASE=stocks
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: debug_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=stocks
      - POSTGRES_USER=treasury
      - POSTGRES_PASSWORD=stockspass
volumes:
  dbdata:
networks: 
  default:
    name: debug_api
